name: DukeKFILM
favicon: null
layout_spectrum: 0.76143
typography_spectrum: 0.49251
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#fcfcfc'
    - '#6b6b6b'
    - '#cecece'
    - '#ababab'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
